### ISSUE TITLE
Error line 17

### ISSUE THREAD

**Issue by didiercedric** [didiercedric/TSP-Optimization#1]
ValueError                                Traceback (most recent call last)
[<ipython-input-3-023f0104a568>](https://localhost:8080/#) in <cell line: 25>()
     27     points = [(0, 0), (1, 5), (2, 3), (5, 2)]
     28 
---> 29     best_order, best_distance = tsp_bruteforce(points)
     30     print("Best order:", best_order)
     31     print("Best distance:", best_distance)

[<ipython-input-3-023f0104a568>](https://localhost:8080/#) in tsp_bruteforce(points)
     15 def tsp_bruteforce(points):
     16     best_order = None
---> 17     best_distance = float('int')
     18     for order in itertools.permutations(range(len(points))):
     19         distance = total_distance(points, order)

ValueError: could not convert string to float: 'int'

**Comment by wafaajaunnoo** [comment]
Your first mistake is that you attempted to solve an optimization problem using brute force and not an evolutionary optimization algorithm.   3 of the most efficient evolutionary algorithsm that you can use to solve TSP are GA, PSO, ACO.  Start from there.

Your second mistake is that you typed "int" instead of "inf". in brute force, you initialize `best_distance` to `float('inf')` to guarantee that the first tour will be stored as the best one initially.  The value `float('inf')` represents **positive infinity** in Python.

**Comment by didiercedric** [comment]
Thanks man! Silly me 🥲
I tried the PSO but NOTHING is working! And I can't understand anything in it. That's why I resorted to BF.

**Comment by wafaajaunnoo** [comment]
happy to help.  try ACO instead, its concept is easier to understand.   lmk if you have any issues!

**Comment by didiercedric** [comment]
Will definitely do 🤣
